In [1]:
def first(iterable):
    if isinstance(iterable, dict):
        return next(iter(iterable.items()))
    return next(iter(iterable))

In [2]:
import pandas
from pandas import read_csv
countpath = r"D:\josiah\Documents\Research\Thesis - Genome Symmetry\DNA_Duplications\CAFE-4.2\data\2020\Feb08_merged_homeolog_counts.csv"
table = read_csv(countpath, delimiter='\t', index_col='Family ID')

table.tail(20)

,FRAX00,FRAX01,FRAX03,FRAX04,FRAX05,FRAX06,FRAX07,FRAX08,FRAX09,FRAX11,...,FRAX25,FRAX26,FRAX27,FRAX28,FRAX29,FRAX30,FRAX31,FRAX32,FRAX33,Oeuropea
Family ID,,,,,,,,,,,,,,,,,,,,,
10020553,0,2,0,0,0,0,0,0,0,0,...,0,0,1,1,0,0,1,0,0,2
10020589,0,0,0,0,0,0,0,1,2,0,...,0,1,0,0,1,0,0,0,0,2
10020620,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,2
10020636,1,0,0,1,0,1,1,0,2,0,...,0,0,0,0,0,0,1,0,0,2
10020710,0,0,0,0,0,0,0,0,1,1,...,0,0,1,0,0,0,0,0,0,2
10020721,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
10020737,0,1,0,1,2,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,2
10020838,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,2
10020856,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,2
10020885,1,0,0,1,0,0,0,0,0,1,...,1,0,0,1,0,0,0,0,0,2
10021109,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,2
10021284,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
10021314,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,2
10021342,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,2
10021349,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
10021364,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,3
10021572,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
10021601,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
10021789,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
10021837,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3

**Note that the table is sorted by total gene count, so the tail has gene families with very few members. This means some amount of gene loss overlap between species is non-random because the families themselves are rare across all species. This can most easily be explained by deep ancestral losses which are not necessarily polyphyletic.***

In [13]:
def geneLossSet(threshold):
    """Gene families below the threshold will be returned."""
    genesLost = dict()
    for species, familyCounts in table.iteritems(): 
        genesLost[species] = set()
        for fam, count in zip(familyCounts.index.values, familyCounts):
            if species == "Oeuropea": 
                count -= threshold # compensate for extra WGD
            if count < threshold:
    #             print(fam)
                genesLost[species].add(fam)
    return genesLost
singleLosses = geneLossSet(2)
doubleLosses = geneLossSet(1)

### Single Losses

In [16]:
for species, familyCounts in table.iteritems(): 
    print(species, len(singleLosses[species]))

FRAX00 1245
FRAX01 1701
FRAX03 1769
FRAX04 1690
FRAX05 1665
FRAX06 1331
FRAX07 1288
FRAX08 1904
FRAX09 1099
FRAX11 1086
FRAX12 1895
FRAX13 1740
FRAX14 1860
FRAX15 1971
FRAX16 2126
FRAX19 1298
FRAX20 2000
FRAX21 1882
FRAX23 1909
FRAX25 1998
FRAX26 1487
FRAX27 1473
FRAX28 1665
FRAX29 1784
FRAX30 1721
FRAX31 1360
FRAX32 1647
FRAX33 1501
Oeuropea 3860

### Double Losses

In [5]:
for species, familyCounts in table.iteritems(): 
    print(len(doubleLosses[species]))

232
402
496
403
425
321
290
556
279
277
542
455
495
558
577
328
566
520
499
536
350
348
427
507
446
330
414
377
0

# Overlap Table

In [59]:
def outputTableFile(losses, tablepath):
    species = table.columns.tolist()
    overlapSingle = []
    for a in species:
        row = []
        for b in species:
            row.append(len(losses[a].intersection(losses[b])))
        overlapSingle.append(row)


    with open(tablepath, 'w') as outfile:
        outfile.write('\t'.join(species) +'\n')
        for row in overlapSingle:
            outfile.write('\t'.join([str(x) for x in row]) +'\n')
            
filepath = r"D:\josiah\Documents\Research\Thesis - Genome Symmetry\DNA_Duplications\CAFE-4.2\data\2020\Feb08_overlap.csv"  
outputTableFile(singleLosses, filepath)

In [60]:
filepath = r"D:\josiah\Documents\Research\Thesis - Genome Symmetry\DNA_Duplications\CAFE-4.2\data\2020\Feb08_overlap_two_or_more_losses.csv"  
outputTableFile(doubleLosses, filepath)